import type { DatabaseClient } from "@workspace/db";
import { requireSuperAdmin, type Principal } from "../authentication/service";
import { HttpError } from "../../lib/errors";
import { audit } from "../../lib/audit";
import { requireFeature, resolveEntitlements } from "../entitlements/resolver";
import { prepareTenant } from "../tenants/service";
import { applyOrderBranding } from "./order-branding";
import { assertFinalPricing, requestColumns, orderView, event } from "./order-model";
import type { catalogSelection } from "./order-catalog";

/** Caller holds the request row lock. Tenant + master + linkage commit together. */
export async function prepareReviewedWebsite(c: DatabaseClient, p: Principal, row: Record<string, any>,
  selection: Awaited<ReturnType<typeof catalogSelection>>) {
  requireSuperAdmin(p);
  assertFinalPricing(row);
  if (!selection.plan) throw new HttpError(409, "Select a White Label Exchange plan before preparing this order.");
  if (row.tenantId) return orderView(c, row); // Never replace an existing customer's settings.
  const tenant = await prepareTenant(c, p, {
    name: row.configuration.brandName, slug: `wl-${row.id}`, planId: selection.plan.id,
  }, selection.addons.map(a => a.id));
  await c.query("UPDATE tenant_subscriptions SET billing_period=$2 WHERE tenant_id=$1",
    [tenant.id, row.configuration.billingPeriod === "yearly" ? "yearly" : "monthly"]);
  const effective = await resolveEntitlements(c, tenant.id);
  requireFeature(effective, "website"); requireFeature(effective, "crypto_exchange");
  for (const action of row.configuration.actions as string[]) requireFeature(effective, action);
  // Approval now grants the isolated master website and its Admin Panel immediately.
  // Do not copy NovaX demo assets/rates/orders or pretend Exchange setup is complete.
  const status = "delivered";
  await applyOrderBranding(c, tenant.id, tenant.slug, row as { id: string; configuration: Record<string, any> });
  await c.query("UPDATE tenants SET status='active',updated_at=now() WHERE id=$1", [tenant.id]);
  await c.query(`INSERT INTO tenant_memberships(tenant_id,clerk_user_id,role,label,active)
    VALUES($1,$2,'client_admin','Customer account owner',true)
    ON CONFLICT(tenant_id,clerk_user_id) DO UPDATE SET role='client_admin',active=true`,
    [tenant.id, row.customerUserId]);
  const prepared = await c.query(`UPDATE white_label_requests SET tenant_id=$2,status=$3,updated_at=now()
    WHERE id=$1 RETURNING ${requestColumns}`, [row.id, tenant.id, status]);
  await event(c, p, row.id, "status", "Approved: your isolated NovaX-master website and Admin Panel are available in your existing account. Exchange routes and integrations still require your tenant's configuration. All financial operations remain Sandbox; custom design work is not generated by approval.", "customer", status);
  await audit(c, p, tenant.id, "white_label.provisioned", "Approval provisioned the isolated master website and customer Admin; financial configuration is separate", { requestId: row.id });
  return orderView(c, prepared.rows[0]);
}
