import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { pool, withDatabase } from "@workspace/db";
import { resolvePrincipal } from "../modules/authentication/service";
import { myAdminPanels, listRequests, submitRequest, reviewRequest, deliverRequest, assertDeliveredExchangeAccess, orderDetail, appendNote } from "../modules/customer/service";
import { whiteLabelCatalog } from "../modules/customer/order-catalog";
import { activateTenant, createTenant, getTenant, saveBrand, saveDomain, saveAssets, saveConfiguration } from "../modules/tenants/service";
import { GetTenantResponse } from "@workspace/api-zod";
import { getPublicSite } from "../modules/website/service";
import { emptyPreviewSettings, previewIntegrations } from "../products/exchange/preview-integrations";
import { exchangeConfiguration, publicExchange } from "../products/exchange/service";
import { resolveEntitlements } from "../modules/entitlements/resolver";
import { prepareCustomerFixtures, finishCustomerTenant, cleanCustomerFixtures } from "./customer-fixtures";
if (process.env.NODE_ENV === "production") throw new Error("Development verification refused in production.");
const suffix = randomUUID().slice(0, 8);
const actors = [`user_workflowOperator${suffix}`, `user_workflowCustomer${suffix}`, `user_workflowOther${suffix}`];
let fixture: Awaited<ReturnType<typeof prepareCustomerFixtures>> | undefined;
let draftId: string | undefined;
const autoTenantIds: string[] = [];
const denied = (fn: () => Promise<unknown>, status: number | string) => assert.rejects(async () => fn(), (e: any) => e.status === status || e.code === status);
try {
  await pool.query("INSERT INTO platform_admins (clerk_user_id) VALUES ($1)", [actors[0]]);
  const op = await resolvePrincipal(actors[0]), a = await resolvePrincipal(actors[1]), b = await resolvePrincipal(actors[2]);
  assert.equal(a.role, "unassigned");
  assert.deepEqual(await myAdminPanels(a), []);
  const input = { projectName: "My Exchange A", brandName: "My Exchange", preferredDomain: null, actions: ["swap", "convert", "buy", "sell"] as ("swap" | "convert" | "buy" | "sell")[], details: "Sandbox only", idempotencyKey: randomUUID() };
  const submitted = await submitRequest(a, input);
  assert.match(submitted.orderReference, /^WL-\d{6,}$/);
  assert.equal(submitted.status, "new");
  assert.equal((await submitRequest(a, input)).id, submitted.id);
  assert.equal((await listRequests(a)).length, 1);
  assert.equal((await listRequests(b)).length, 0);
  await denied(() => listRequests(a, true), 403);
  const price = { status: "approved" as const, monthlyPrice: "149", setupPrice: "299", currency: "USD" as const, operatorNote: "Sandbox preparation" };
  await denied(() => reviewRequest(a, submitted.id, price), 403);
  await denied(() => orderDetail(b, submitted.id), 404);
  await denied(() => appendNote(a, submitted.id, { message: "Escalation", visibility: "internal" }), 403);
  await appendNote(op, submitted.id, { message: "PRIVATE WORKFLOW VERIFICATION", visibility: "internal" });
  await appendNote(op, submitted.id, { message: "We are reviewing your project.", visibility: "customer" });
  assert.ok((await orderDetail(op, submitted.id, true)).history.some(n => n.visibility === "internal"));
  assert.ok(!(await orderDetail(a, submitted.id)).history.some(n => n.visibility === "internal" || n.message.includes("PRIVATE WORKFLOW")));
  await denied(() => reviewRequest(op, submitted.id, { ...price, status: "ready" }), 409);
   assert.equal((await orderDetail(a, submitted.id)).order.status, "new");
   assert.equal((await orderDetail(a, submitted.id)).order.monthlyPrice, null);
   await denied(() => orderDetail(a, submitted.id, true), 403);
  fixture = await prepareCustomerFixtures(op, suffix);
  assert.ok((await whiteLabelCatalog(a)).plans.some(p => p.id === fixture!.planId));
  const custom = await submitRequest(a, { ...input, companyName: "Verification Company", requestedPlanId: fixture.planId, requestedAddonIds: [], billingPeriod: "yearly", attachmentIds: [],
    details: "Requirements ".repeat(200), idempotencyKey: randomUUID(),
    design: { type: "custom", styleName: "Custom verification", primaryColor: "#112233", accentColor: "#abcdef", themePreference: "both", description: "Operator-reviewed paid customization",
      referenceWebsiteUrl: "https://example.com", notes: "No automated implementation", logoAttachmentId: null, faviconAttachmentId: null, referenceAttachmentIds: [] } });
  assert.equal(custom.companyName, "Verification Company");
  assert.equal(custom.billingPeriod, "yearly");
  assert.equal(custom.requestedPlan.id, fixture.planId);
  await denied(() => reviewRequest(op, custom.id, price), 409);
  const preparedCustom = await reviewRequest(op, custom.id, { ...price, customizationPrice: "500", customDesignDecision: "approved", approvedPlanId: fixture.planId, approvedAddonIds: [] });
   assert.equal(preparedCustom.status, "delivered");
  assert.ok(preparedCustom.tenantId);
  autoTenantIds.push(preparedCustom.tenantId!);
  assert.deepEqual(await myAdminPanels(a), []);
   await denied(() => reviewRequest(op, custom.id, { ...price, monthlyPrice: "175", customizationPrice: "600", customDesignDecision: "approved", status: "in_setup" }), 409);
  const customDetail = await orderDetail(a, custom.id);
   assert.equal(customDetail.order.monthlyPrice, "149");
   assert.equal(customDetail.order.customizationPrice, "500");
   assert.ok(customDetail.history.some(h => h.status === "delivered"));
  const [first] = fixture.tenants;
  const draft = await createTenant(op, { name: "Not delivered", slug: `workflow-draft-${suffix}`, planId: fixture.planId }); draftId = draft.id;
  await pool.query("INSERT INTO tenant_memberships (tenant_id,clerk_user_id,role) VALUES ($1,$2,'client_admin')", [draft.id, a.userId]);
  const withDraft = await resolvePrincipal(a.userId);
   assert.ok(!(await myAdminPanels(withDraft)).some(panel => panel.tenantId === draft.id));
  await denied(() => assertDeliveredExchangeAccess(withDraft, draft.id), 403);
  await denied(() => activateTenant(withDraft, draft.id), 403);
  await saveBrand(op, draft.id, { brandName: draft.brandName, logoUrl: null, primaryColor: "#102C36", accentColor: "#44D7C4", themeMode: "system", defaultLanguage: "en", supportedLanguages: ["en"] });
  await saveDomain(op, draft.id, null);
  await saveAssets(op, draft.id, fixture.base.networks.map(network => network.assetNetworkId));
  await saveConfiguration(op, draft.id, { environment: "sandbox", exchangeEnabled: false, paymentsEnabled: false, allowGuestCheckout: false });
  await previewIntegrations(op, draft.id, { settings: emptyPreviewSettings() });
  const previewOnly = await activateTenant(op, draft.id);
  assert.equal(previewOnly.status, "active", "Inert optional settings must not block an unrelated visual preview.");
  assert.equal(previewOnly.exchangeProvisioned, false, "A metadata row must never mark an operational Exchange provisioned.");
  await denied(() => assertDeliveredExchangeAccess(withDraft, draft.id), 403);
   assert.ok(!(await myAdminPanels(withDraft)).some(panel => panel.tenantId === draft.id));
  await denied(() => deliverRequest(a, submitted.id, first.id), 403);
  await denied(() => deliverRequest(op, submitted.id, first.id), 409);
  await denied(() => reviewRequest(op, submitted.id, price), 409);
  const prepared = await reviewRequest(op, submitted.id, { ...price, approvedPlanId: fixture.planId, approvedAddonIds: [] });
   assert.equal(prepared.status, "delivered");
  assert.ok(prepared.tenantId);
  autoTenantIds.push(prepared.tenantId!);
  assert.equal((await myAdminPanels(a)).length, 0);
  assert.deepEqual((await previewIntegrations(op, prepared.tenantId!)).settings, emptyPreviewSettings());
  await previewIntegrations(op, prepared.tenantId!, { settings: emptyPreviewSettings() });
  assert.equal((await getTenant(op, prepared.tenantId!)).configurationComplete, false, "Preview settings never count as operational provisioning.");
  // Reproduce the reported case: every legacy step is complete, but no Exchange was saved.
  await saveBrand(op, prepared.tenantId!, { brandName: prepared.brandName, logoUrl: null, primaryColor: "#102C36", accentColor: "#44D7C4", themeMode: "system", defaultLanguage: "en", supportedLanguages: ["en"] });
  await saveDomain(op, prepared.tenantId!, null);
  await saveAssets(op, prepared.tenantId!, fixture.base.networks.map(network => network.assetNetworkId));
  await saveConfiguration(op, prepared.tenantId!, { environment: "sandbox", exchangeEnabled: true, paymentsEnabled: false, allowGuestCheckout: false });
  const blocked = GetTenantResponse.parse(await getTenant(op, prepared.tenantId!));
  assert.equal(blocked.configurationComplete, false, "Legacy completed steps must not falsely report an Exchange Ready.");
  assert.equal(blocked.provisioningStep, "configuration");
  assert.ok(blocked.activationBlockers?.some(message => message.includes("Save the Exchange setup")));
  await denied(() => activateTenant(op, prepared.tenantId!), 400);
   assert.equal((await getTenant(op, prepared.tenantId!)).status, "active");
   assert.equal((await orderDetail(a, submitted.id)).order.status, "delivered");
   assert.ok((await myAdminPanels(await resolvePrincipal(a.userId))).some(panel => panel.tenantId === prepared.tenantId), "Approval grants Admin access independently of financial setup readiness.");
  await denied(() => deliverRequest(op, submitted.id, draft.id), 409);
  await denied(() => deliverRequest(op, submitted.id, first.id), 409);
  await finishCustomerTenant(op, { id: prepared.tenantId!, name: prepared.brandName }, fixture.base);
  const readyConfiguration = (await exchangeConfiguration(op, prepared.tenantId!)).configuration;
  await exchangeConfiguration(op, prepared.tenantId!, { ...readyConfiguration, routes: readyConfiguration.routes.filter(route => route.action !== "sell") });
  const missingAction = await getTenant(op, prepared.tenantId!);
  assert.equal(missingAction.configurationComplete, false);
  assert.ok(missingAction.activationBlockers.some(message => message.includes("requested sell")));
  await denied(() => activateTenant(op, prepared.tenantId!), 400);
  await exchangeConfiguration(op, prepared.tenantId!, readyConfiguration);
  assert.equal((await getTenant(op, prepared.tenantId!)).configurationComplete, true);
  await activateTenant(op, prepared.tenantId!);
  await deliverRequest(op, submitted.id, prepared.tenantId!);
  const owner = await resolvePrincipal(a.userId);
   assert.equal((await myAdminPanels(owner)).length, 2);
  await assertDeliveredExchangeAccess(owner, prepared.tenantId!);
  await denied(() => assertDeliveredExchangeAccess(b, prepared.tenantId!), 403);
  assert.deepEqual((await previewIntegrations(owner, prepared.tenantId!)).settings, emptyPreviewSettings(), "Unconfigured optional modules do not prevent automatic delivery.");
  const privatePreview = {
    api: { enabled: true, label: "Private API preview", baseUrl: "https://api.preview.example" },
    webhooks: { enabled: true, label: "Private webhook preview", endpointUrl: "https://hooks.preview.example/events", events: ["order.created", "order.status_changed"] },
    rpc: { enabled: true, label: "Private RPC preview", endpointUrl: "https://rpc.preview.example", networkName: "Sandbox network" },
  };
  const entitlementBefore = await withDatabase({ actorId: op.userId, tenantId: prepared.tenantId!, isSuperAdmin: true }, c => resolveEntitlements(c, prepared.tenantId!));
  assert.equal(entitlementBefore.features.webhooks, false);
  assert.deepEqual((await previewIntegrations(owner, prepared.tenantId!, { settings: privatePreview })).settings, privatePreview);
  const apiOnly = { ...emptyPreviewSettings(), api: { ...privatePreview.api, label: "Updated API preview" } };
  const merged = await previewIntegrations(owner, prepared.tenantId!, { settings: apiOnly, modules: ["api"] });
  privatePreview.api.label = "Updated API preview";
  assert.deepEqual(merged.settings, privatePreview, "Saving one module must not overwrite settings from other tabs or sessions.");
  await denied(() => previewIntegrations(b, prepared.tenantId!), 403);
  await denied(() => previewIntegrations(b, prepared.tenantId!, { settings: privatePreview }), 403);
  await denied(() => previewIntegrations(owner, prepared.tenantId!, { settings: { ...privatePreview, api: { ...privatePreview.api, secret: "DO_NOT_STORE" } } }), 400);
  await denied(() => previewIntegrations(owner, prepared.tenantId!, { settings: { ...privatePreview, api: { ...privatePreview.api, baseUrl: "https://api.preview.example?token=DO_NOT_STORE" } } }), 400);
  await denied(() => previewIntegrations(owner, prepared.tenantId!, { settings: { ...privatePreview, rpc: { ...privatePreview.rpc, networkName: "" } } }), 400);
  const entitlementAfter = await withDatabase({ actorId: op.userId, tenantId: prepared.tenantId!, isSuperAdmin: true }, c => resolveEntitlements(c, prepared.tenantId!));
  assert.deepEqual(entitlementAfter.features, entitlementBefore.features, "Preview switches never grant live module entitlements.");
  const publicBefore = await publicExchange(`wl-${submitted.id}`);
  assert.ok(!JSON.stringify(publicBefore).includes("preview.example"), "Private preview URLs never reach public Exchange responses.");
  const operational = (await exchangeConfiguration(owner, prepared.tenantId!)).configuration;
  await exchangeConfiguration(owner, prepared.tenantId!, operational);
  assert.deepEqual((await previewIntegrations(owner, prepared.tenantId!)).settings, privatePreview, "Operational saves preserve independently edited preview settings.");
  assert.deepEqual(await publicExchange(`wl-${submitted.id}`), publicBefore, "Optional settings never alter public sandbox behavior.");
  await previewIntegrations(owner, prepared.tenantId!, { settings: emptyPreviewSettings() });
  assert.deepEqual((await previewIntegrations(owner, prepared.tenantId!)).settings, emptyPreviewSettings());
  assert.equal((await listRequests(a)).find(r => r.id === submitted.id)?.status, "delivered");
  await finishCustomerTenant(op, { id: preparedCustom.tenantId!, name: preparedCustom.brandName }, fixture.base);
   await pool.query("INSERT INTO tenant_memberships (tenant_id,clerk_user_id,role) VALUES ($1,$2,'client_admin') ON CONFLICT(tenant_id,clerk_user_id) DO NOTHING", [preparedCustom.tenantId, a.userId]);
  await activateTenant(op, preparedCustom.tenantId!);
   assert.equal((await orderDetail(a, custom.id)).order.status, "delivered");
   assert.equal((await myAdminPanels(await resolvePrincipal(a.userId))).length, 2);
   assert.equal((await getPublicSite(`wl-${custom.id}`)).tenantSlug, `wl-${custom.id}`);
   await denied(() => reviewRequest(op, custom.id, { ...price, monthlyPrice: "175", customizationPrice: "600", customDesignDecision: "approved", status: "ready" }), 409);
  assert.equal((await orderDetail(a, custom.id)).order.status, "delivered");
  assert.equal((await getPublicSite(`wl-${custom.id}`)).tenantSlug, `wl-${custom.id}`);
  const foreign = await submitRequest(b, { ...input, projectName: "Other customer", idempotencyKey: randomUUID() });
  const foreignPrepared = await reviewRequest(op, foreign.id, { ...price, approvedPlanId: fixture.planId, approvedAddonIds: [] });
  autoTenantIds.push(foreignPrepared.tenantId!);
  await denied(() => deliverRequest(op, foreign.id, first.id), 409);
  const additional = await submitRequest(owner, { ...input, projectName: "My Exchange B", idempotencyKey: randomUUID() });
  const extraPrepared = await reviewRequest(op, additional.id, { ...price, approvedPlanId: fixture.planId, approvedAddonIds: [] });
  autoTenantIds.push(extraPrepared.tenantId!);
  await finishCustomerTenant(op, { id: extraPrepared.tenantId!, name: extraPrepared.brandName }, fixture.base);
  await activateTenant(op, extraPrepared.tenantId!);
  assert.equal((await myAdminPanels(await resolvePrincipal(a.userId))).length, 3);
  assert.equal((await myAdminPanels(await resolvePrincipal(b.userId))).length, 1);
  await pool.query("UPDATE tenant_memberships SET active=false WHERE clerk_user_id=$1", [a.userId]);
  assert.deepEqual(await myAdminPanels(await resolvePrincipal(a.userId)), []);
  console.log("PASS: financial setup readiness, missing-config/action rejection, private preview independence, approval delivery without fabricated custom designs, optional settings privacy/save/off, unchanged entitlements and sandbox behavior, idempotency and revocation.");
} finally {
  if (fixture) await cleanCustomerFixtures([...fixture.tenants.map(t => t.id), ...autoTenantIds, ...(draftId ? [draftId] : [])], fixture.planId, actors);
  else { await pool.query("DELETE FROM white_label_requests WHERE customer_user_id=ANY($1::text[])", [actors]); await pool.query("DELETE FROM platform_admins WHERE clerk_user_id=ANY($1::text[])", [actors]); }
  await pool.end();
}